[module]
[[module.imports]]
  ignoreConfig = true
  path = "github.com/andreknieriem/simplelightbox"
  disabled = false
[[module.imports.mounts]]
  source="dist/simple-lightbox.min.js"
  target="static/js/simple-lightbox.min.js"
[[module.imports.mounts]]
  source="dist/simple-lightbox.min.css"
  target="static/css/simple-lightbox.min.css"
